spring.application.name=mart

# DB 서버 연동 정보 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springdb
spring.datasource.username=java_db
spring.datasource.password=12345

#이건 오라클db 연동
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
# spring.datasource.username=java_db
# spring.datasource.password=12345



# 원래는 dialect을 자동으로 잡아주는데 나는 안돼서 수동으로 연결시킴
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# jpa로 작업할때는 테이블을 자동생성할 수 있다!
# =none : 운영환경(개발이 다 끝나고 운영할때)
# =validate : entity와 table의 정상 매핑 확인(운영환경)
# =create : 기본테이블 삭제 후 테이블 생성(개발시)
# =create-drop : 기본 테이블 삭제 후 테이블 생성, 종료 시점에 테이블 삭제(개발시)
# =update : 변경된 부분만 적용(기존 변경 전 컬럼 제거는 해주지 않는다)
spring.jpa.hibernate.ddl-auto=validate
# 생성되는 sql구문 출력 여부(hibernate)
# spring.jpa.show-sql=true
# 가독성 좋게 이쁘게 출력해줘~
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# 로그출력(개발용)
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace