spring.application.name=movietalk

# DB 서버 연동 정보 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/movie
spring.datasource.username=java_db
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update

# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# thymeleaf
# 만들어진 결과 캐쉬로 보관해말아
spring.thymeleaf.cache=false

# 여러 개의 properties 생성 가능
spring.profiles.include=oauth

# 파일 업로드 설정
# 파일 업로드 가능 여부
spring.servlet.multipart.enabled=true
# 업로드된 파일의 임시 저장 경로
# spring.servlet.multipart.location=c:\\upload
# 파일 하나의 최대 크기
spring.servlet.multipart.max-file-size=10MB
# 한 번에 최대 업로드 가능한 용량 설정
spring.servlet.multipart.max-request-size=30MB

# 실제 파일이 업로드 될 경로(클래스파일에서 호출)
com.example.movietalk.upload.path=c:\\upload
# 프로젝트 내에 폴더가 생성됨
# com.example.movietalk.upload.path=upload
