spring:
  application:
    name: ai

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5-nano
          temperature: 1.0
      embedding:
        options:
          model: text-embedding-3-small
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/react
    username: java_db
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
